_wandb:
    value:
        cli_version: 0.21.3
        e:
            sy633ngaa62igpgiyj3ac4ccpxl22bsg:
                args:
                    - use_bio_probability=False
                codePath: ec.py
                codePathLocal: ec.py
                cpu_count: 5
                cpu_count_logical: 10
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1081101176832"
                        used: "151009587200"
                email: 3102259390@qq.com
                executable: /home/mzsk/miniconda3/envs/ec_py309/bin/python
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-95140831-d184-a55e-29ee-17d461e54cbc
                host: r
                memory:
                    total: "12542763008"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/mzsk/code/EvolvingConnectivity-master/ec.py
                python: CPython 3.9.23
                root: /home/mzsk/code/EvolvingConnectivity-master
                startedAt: "2025-12-23T15:28:04.081273Z"
                writerId: sy633ngaa62igpgiyj3ac4ccpxl22bsg
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 12
                - 35
                - 45
            "2":
                - 12
                - 35
                - 45
            "3":
                - 3
                - 13
                - 16
                - 61
            "4": 3.9.23
            "5": 0.21.3
            "10":
                - 20
            "12": 0.21.3
            "13": linux-x86_64
episode_conf:
    value:
        action_repeat: 1
        max_episode_length: 1000
network_conf:
    value:
        excitatory_ratio: 0.7642436149312377
        num_neurons: 509
network_type:
    value: ConnSNN
project_name:
    value: E-SNN-humanoid
run_name:
    value: EC 0 ConnSNN 23:27 12-23
save_every:
    value: 50
save_model_path:
    value: models/E-SNN-humanoid/EC 0 ConnSNN 23:27 12-23/
seed:
    value: 0
task:
    value: humanoid
total_generations:
    value: 1000
use_bio_probability:
    value: false
